version: '3.5'

services:
  chaos-ws:
    image: ${REGISTRY_HOST}/chaos/chaos-ws:${VERSION}
    depends_on:
      - chaos-ws-redis
    networks:
      - chaos
      - lb-common
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - NAVITIA_URL=${NAVITIA_URL}
      - NAVITIA_TIMEOUT=${NAVITIA_TIMEOUT}
      - RABBITMQ_CONNECTION_STRING=${RABBITMQ_CONNECTION_STRING}
      - CACHE_REDIS_HOST=${CACHE_REDIS_HOST}
      - IMPACT_EXPORT_DIR=${IMPACT_EXPORT_DIR}
      - NEW_RELIC_CONFIG_FILE=${NEW_RELIC_CONFIG_FILE}
    logging:
     driver: "fluentd"
      options:
       tag: chaos.ws.http
       fluentd-async-connect: "true"
    deploy:
      replicas: "${REPLICAS_CHAOS_WS}"
      labels:
        - "traefik.frontend.rule=Host:chaos-${ENV}.navitia.io,chaos-${ENV}.canaltp.prod"
        - "traefik.docker.network=lb-common"
        - "traefik.port=5000"
        - "traefik.frontend.entryPoints=http"
        - "traefik.enable=true"
    volumes:
      - ${IMPACT_EXPORT_DIR}:/data/exports:rw
      - ${NEW_RELIC_CONFIG_FILE}:/conf/newrelic.ini:ro

  chaos-ws-redis:
    image: redis:${REDIS_VERSION}
    networks:
      - chaos

networks:
  chaos:
    name: chaos_network
    driver: overlay
  lb-common:
    external: true
